<?php

// Data functions (insert, update, delete, form) for table Ads

// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

function Ads_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('Ads');
	if(!$arrPerm[1]){
		return false;
	}

	$data['CreatedOn'] = parseCode('<%%creationDate%%>', true);
	$data['NickName'] = makeSafe($_REQUEST['NickName']);
		if($data['NickName'] == empty_lookup_value){ $data['NickName'] = ''; }
	$data['Sex'] = makeSafe($_REQUEST['Sex']);
		if($data['Sex'] == empty_lookup_value){ $data['Sex'] = ''; }
	$data['Age'] = makeSafe($_REQUEST['Age']);
		if($data['Age'] == empty_lookup_value){ $data['Age'] = ''; }
	$data['Status'] = makeSafe($_REQUEST['Status']);
		if($data['Status'] == empty_lookup_value){ $data['Status'] = ''; }
	$data['InterestedIn'] = makeSafe($_REQUEST['InterestedIn']);
		if($data['InterestedIn'] == empty_lookup_value){ $data['InterestedIn'] = ''; }
	$data['MoreInfo'] = makeSafe($_REQUEST['MoreInfo']);
		if($data['MoreInfo'] == empty_lookup_value){ $data['MoreInfo'] = ''; }
	$data['Contact'] = makeSafe($_REQUEST['Contact']);
		if($data['Contact'] == empty_lookup_value){ $data['Contact'] = ''; }
	$data['Pic1'] = PrepareUploadedFile('Pic1', 5273600,'jpg|jpeg|gif|png', false, '');
	$data['Pic2'] = PrepareUploadedFile('Pic2', 5242880,'jpg|jpeg|gif|png', false, '');
	$data['Pic3'] = PrepareUploadedFile('Pic3', 5242880,'jpg|jpeg|gif|png', false, '');

	/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
	if($_REQUEST['SelectedID']){
		$res = sql("select * from Ads where id='" . makeSafe($_REQUEST['SelectedID']) . "'", $eo);
		if($row = db_fetch_assoc($res)){
			if(!$data['Pic1']) $data['Pic1'] = makeSafe($row['Pic1']);
			if(!$data['Pic2']) $data['Pic2'] = makeSafe($row['Pic2']);
			if(!$data['Pic3']) $data['Pic3'] = makeSafe($row['Pic3']);
		}
	}

	// hook: Ads_before_insert
	if(function_exists('Ads_before_insert')){
		$args=array();
		if(!Ads_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `Ads` set       `CreatedOn`=' . "'{$data['CreatedOn']}'" . ', `NickName`=' . (($data['NickName'] !== '' && $data['NickName'] !== NULL) ? "'{$data['NickName']}'" : 'NULL') . ', `Sex`=' . (($data['Sex'] !== '' && $data['Sex'] !== NULL) ? "'{$data['Sex']}'" : 'NULL') . ', `Age`=' . (($data['Age'] !== '' && $data['Age'] !== NULL) ? "'{$data['Age']}'" : 'NULL') . ', `Status`=' . (($data['Status'] !== '' && $data['Status'] !== NULL) ? "'{$data['Status']}'" : 'NULL') . ', `InterestedIn`=' . (($data['InterestedIn'] !== '' && $data['InterestedIn'] !== NULL) ? "'{$data['InterestedIn']}'" : 'NULL') . ', ' . ($data['Pic1'] != '' ? "`Pic1`='{$data['Pic1']}'" : '`Pic1`=NULL') . ', ' . ($data['Pic2'] != '' ? "`Pic2`='{$data['Pic2']}'" : '`Pic2`=NULL') . ', ' . ($data['Pic3'] != '' ? "`Pic3`='{$data['Pic3']}'" : '`Pic3`=NULL') . ', `MoreInfo`=' . (($data['MoreInfo'] !== '' && $data['MoreInfo'] !== NULL) ? "'{$data['MoreInfo']}'" : 'NULL') . ', `Contact`=' . (($data['Contact'] !== '' && $data['Contact'] !== NULL) ? "'{$data['Contact']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"Ads_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: Ads_after_insert
	if(function_exists('Ads_after_insert')){
		$res = sql("select * from `Ads` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Ads_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='Ads', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function Ads_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Ads');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Ads' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Ads' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Ads_before_delete
	if(function_exists('Ads_before_delete')){
		$args=array();
		if(!Ads_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Ads` where `id`='$selected_id'", $eo);

	// hook: Ads_after_delete
	if(function_exists('Ads_after_delete')){
		$args=array();
		Ads_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Ads' and pkValue='$selected_id'", $eo);
}

function Ads_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Ads');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Ads' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Ads' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['NickName'] = makeSafe($_REQUEST['NickName']);
		if($data['NickName'] == empty_lookup_value){ $data['NickName'] = ''; }
	$data['Sex'] = makeSafe($_REQUEST['Sex']);
		if($data['Sex'] == empty_lookup_value){ $data['Sex'] = ''; }
	$data['Age'] = makeSafe($_REQUEST['Age']);
		if($data['Age'] == empty_lookup_value){ $data['Age'] = ''; }
	$data['Status'] = makeSafe($_REQUEST['Status']);
		if($data['Status'] == empty_lookup_value){ $data['Status'] = ''; }
	$data['InterestedIn'] = makeSafe($_REQUEST['InterestedIn']);
		if($data['InterestedIn'] == empty_lookup_value){ $data['InterestedIn'] = ''; }
	$data['MoreInfo'] = makeSafe($_REQUEST['MoreInfo']);
		if($data['MoreInfo'] == empty_lookup_value){ $data['MoreInfo'] = ''; }
	$data['Contact'] = makeSafe($_REQUEST['Contact']);
		if($data['Contact'] == empty_lookup_value){ $data['Contact'] = ''; }
	$data['selectedID']=makeSafe($selected_id);
	if($_REQUEST['Pic1_remove'] == 1){
		$data['Pic1'] = '';
	}else{
		$data['Pic1'] = PrepareUploadedFile('Pic1', 5273600, 'jpg|jpeg|gif|png', false, "");
	}
	if($_REQUEST['Pic2_remove'] == 1){
		$data['Pic2'] = '';
	}else{
		$data['Pic2'] = PrepareUploadedFile('Pic2', 5242880, 'jpg|jpeg|gif|png', false, "");
	}
	if($_REQUEST['Pic3_remove'] == 1){
		$data['Pic3'] = '';
	}else{
		$data['Pic3'] = PrepareUploadedFile('Pic3', 5242880, 'jpg|jpeg|gif|png', false, "");
	}

	// hook: Ads_before_update
	if(function_exists('Ads_before_update')){
		$args=array();
		if(!Ads_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `Ads` set       `CreatedOn`=`CreatedOn`' . ', `NickName`=' . (($data['NickName'] !== '' && $data['NickName'] !== NULL) ? "'{$data['NickName']}'" : 'NULL') . ', `Sex`=' . (($data['Sex'] !== '' && $data['Sex'] !== NULL) ? "'{$data['Sex']}'" : 'NULL') . ', `Age`=' . (($data['Age'] !== '' && $data['Age'] !== NULL) ? "'{$data['Age']}'" : 'NULL') . ', `Status`=' . (($data['Status'] !== '' && $data['Status'] !== NULL) ? "'{$data['Status']}'" : 'NULL') . ', `InterestedIn`=' . (($data['InterestedIn'] !== '' && $data['InterestedIn'] !== NULL) ? "'{$data['InterestedIn']}'" : 'NULL') . ', ' . ($data['Pic1']!='' ? "`Pic1`='{$data['Pic1']}'" : ($_REQUEST['Pic1_remove'] != 1 ? '`Pic1`=`Pic1`' : '`Pic1`=NULL')) . ', ' . ($data['Pic2']!='' ? "`Pic2`='{$data['Pic2']}'" : ($_REQUEST['Pic2_remove'] != 1 ? '`Pic2`=`Pic2`' : '`Pic2`=NULL')) . ', ' . ($data['Pic3']!='' ? "`Pic3`='{$data['Pic3']}'" : ($_REQUEST['Pic3_remove'] != 1 ? '`Pic3`=`Pic3`' : '`Pic3`=NULL')) . ', `MoreInfo`=' . (($data['MoreInfo'] !== '' && $data['MoreInfo'] !== NULL) ? "'{$data['MoreInfo']}'" : 'NULL') . ', `Contact`=' . (($data['Contact'] !== '' && $data['Contact'] !== NULL) ? "'{$data['Contact']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="Ads_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Ads_after_update
	if(function_exists('Ads_after_update')){
		$res = sql("SELECT * FROM `Ads` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Ads_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='Ads' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function Ads_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Ads');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Sex
	$combo_Sex = new Combo;
	$combo_Sex->ListType = 2;
	$combo_Sex->MultipleSeparator = ', ';
	$combo_Sex->ListBoxHeight = 10;
	$combo_Sex->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Ads.Sex.csv')){
		$Sex_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Ads.Sex.csv')));
		$combo_Sex->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($Sex_data)));
		$combo_Sex->ListData = $combo_Sex->ListItem;
	}else{
		$combo_Sex->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Male;;Female")));
		$combo_Sex->ListData = $combo_Sex->ListItem;
	}
	$combo_Sex->SelectName = 'Sex';
	// combobox: Status
	$combo_Status = new Combo;
	$combo_Status->ListType = 0;
	$combo_Status->MultipleSeparator = ', ';
	$combo_Status->ListBoxHeight = 10;
	$combo_Status->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Ads.Status.csv')){
		$Status_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Ads.Status.csv')));
		$combo_Status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($Status_data)));
		$combo_Status->ListData = $combo_Status->ListItem;
	}else{
		$combo_Status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Single;;Married;;Seperated;;Widowed")));
		$combo_Status->ListData = $combo_Status->ListItem;
	}
	$combo_Status->SelectName = 'Status';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Ads' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Ads' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `Ads` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_Sex->SelectedData = $row['Sex'];
		$combo_Status->SelectedData = $row['Status'];
	}else{
		$combo_Sex->SelectedText = ( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_Status->SelectedText = ( $_REQUEST['FilterField'][1]=='6' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_Sex->Render();
	$combo_Status->Render();

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/Ads_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/Ads_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Ad Details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Ads_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Ads_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Ads_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#NickName').replaceWith('<div class=\"form-control-static\" id=\"NickName\">' + (jQuery('#NickName').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('input[name=Sex]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=Sex]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('#Age').replaceWith('<div class=\"form-control-static\" id=\"Age\">' + (jQuery('#Age').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Status').replaceWith('<div class=\"form-control-static\" id=\"Status\">' + (jQuery('#Status').val() || '') + '</div>'); jQuery('#Status-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#InterestedIn').replaceWith('<div class=\"form-control-static\" id=\"InterestedIn\">' + (jQuery('#InterestedIn').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Pic1').replaceWith('<div class=\"form-control-static\" id=\"Pic1\">' + (jQuery('#Pic1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Pic2').replaceWith('<div class=\"form-control-static\" id=\"Pic2\">' + (jQuery('#Pic2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Pic3').replaceWith('<div class=\"form-control-static\" id=\"Pic3\">' + (jQuery('#Pic3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#MoreInfo').replaceWith('<div class=\"form-control-static\" id=\"MoreInfo\">' + (jQuery('#MoreInfo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Contact').replaceWith('<div class=\"form-control-static\" id=\"Contact\">' + (jQuery('#Contact').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(Sex)%%>', $combo_Sex->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(Sex)%%>', $combo_Sex->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(Status)%%>', $combo_Status->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(Status)%%>', $combo_Status->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(CreatedOn)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(NickName)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Sex)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Age)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Status)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(InterestedIn)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Pic1)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=5273600>'.$Translation['upload image'].' <input type="file" name="Pic1" id="Pic1">'), $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Pic2)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=5242880>'.$Translation['upload image'].' <input type="file" name="Pic2" id="Pic2">'), $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Pic3)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=5242880>'.$Translation['upload image'].' <input type="file" name="Pic3" id="Pic3">'), $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(MoreInfo)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Contact)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(CreatedOn)%%>', html_attr($row['CreatedOn']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CreatedOn)%%>', urlencode($urow['CreatedOn']), $templateCode);
		$templateCode=str_replace('<%%VALUE(NickName)%%>', html_attr($row['NickName']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NickName)%%>', urlencode($urow['NickName']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Sex)%%>', html_attr($row['Sex']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Sex)%%>', urlencode($urow['Sex']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Age)%%>', html_attr($row['Age']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Age)%%>', urlencode($urow['Age']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Status)%%>', html_attr($row['Status']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Status)%%>', urlencode($urow['Status']), $templateCode);
		$templateCode=str_replace('<%%VALUE(InterestedIn)%%>', html_attr($row['InterestedIn']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InterestedIn)%%>', urlencode($urow['InterestedIn']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Pic1)%%>', html_attr($row['Pic1']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Pic1)%%>', urlencode($urow['Pic1']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Pic2)%%>', html_attr($row['Pic2']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Pic2)%%>', urlencode($urow['Pic2']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Pic3)%%>', html_attr($row['Pic3']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Pic3)%%>', urlencode($urow['Pic3']), $templateCode);
		$templateCode=str_replace('<%%VALUE(MoreInfo)%%>', html_attr($row['MoreInfo']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MoreInfo)%%>', urlencode($urow['MoreInfo']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Contact)%%>', html_attr($row['Contact']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Contact)%%>', urlencode($urow['Contact']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(CreatedOn)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CreatedOn)%%>', urlencode('<%%creationDate%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(NickName)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NickName)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Sex)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Sex)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Age)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Age)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Status)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Status)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(InterestedIn)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(InterestedIn)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Pic1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Pic1)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Pic2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Pic2)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Pic3)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Pic3)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(MoreInfo)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MoreInfo)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Contact)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Contact)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: Ads_dv
	if(function_exists('Ads_dv')){
		$args=array();
		Ads_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>